/// Flutter icons XMIconfont
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  XMIconfont
///      fonts:
///       - asset: fonts/XMIconfont.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class XMIconfont {
  XMIconfont._();

  static const _kFontFam = 'XMIconfont';
  static const String? _kFontPkg = null;

  static const IconData moonStar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appIcon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
